### ISSUE TITLE
net.krafting.SemantiK.Lang.English was of type addon but had no extends

### ISSUE THREAD

**Issue by LeMonMonOTS** [flathub/net.krafting.SemantiK.Lang.English#1]
When I ran `flatpak search something`, flatpak gave:
```
(flatpak search:17641): As-WARNING **: 23:03:12.306: net.krafting.SemantiK.Lang.English was of type addon but had no extends
```

I ran it on `Flatpak 1.12.7` of `Ubuntu 22.04.5 LTS x86_64`.

Is there any idea to solve this warning?

**Comment by organism1000** [comment]
I can reproduce this on an Ubuntu 22.04 VM even with no flatpaks installed.  Merely running "sudo flatpak update" (even without there being any flatpaks installed to update) will produce the "was of type addon but had no extends" warning thereafter every time "flatpak search" or "flatpak remote-ls" is executed.

Maybe this is a similar issue: [https://github.com/flathub/re.rizin.cutter.plugin.rz-ghidra/issues/1](https://github.com/flathub/re.rizin.cutter.plugin.rz-ghidra/issues/1)

**Comment by arnon-weinberg** [comment]
Same issue, fresh install of AlmaLinux 9.4:
```
>flatpak search test
                                                                                
(flatpak search:6250): As-WARNING **: 22:36:18.920: net.krafting.SemantiK.Lang.English was of type addon but had no extends                                     

>flatpak --version
Flatpak 1.12.9
```

**Comment by Krafting** [comment]
https://github.com/flathub/net.krafting.SemantiK.Lang.English/pull/2 Should fix the issue, please let me know (when the update is available) if this fix the issue for you :)

Thank you @GammaGames  for your help

**Comment by GammaGames** [comment]
Flatpak is quiet again! 🎉

**Comment by yermulnik** [comment]
Can this fix please be copied over to https://github.com/flathub/net.krafting.SemantiK.Lang.French?
```shell
> LANG=C flatpak remote-ls --updates

(flatpak remote-ls:2589130): As-WARNING **: 22:12:16.120: net.krafting.SemantiK.Lang.French was of type addon but had no extends
```

**Comment by yermulnik** [comment]
https://github.com/flathub/net.krafting.SemantiK.Lang.French/pull/1
